---
title: "Five_year"
author: "Yiwen Zhao"
date: "12/10/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```


```{r roughly data cleaning, message = FALSE}
crime_2017 =
   read.csv("./data/Crimes_-_2017.csv") %>% 
   drop_na() %>% 
   janitor::clean_names() %>%
   filter(arrest=="true",domestic=="false")
rime_2018 =
   read.csv("./data/Crimes_-_2018.csv") %>% 
   drop_na() %>% 
   janitor::clean_names() %>%
   filter(arrest=="true",domestic=="false")
crime_2019 =
   read.csv("./data/Crimes_-_2019.csv") %>% 
   drop_na() %>% 
   janitor::clean_names() %>%
   filter(arrest=="true",domestic=="false")
crime_2020 =
   read.csv("./data/Crimes_-_2020.csv") %>% 
   drop_na() %>% 
   janitor::clean_names() %>%
   filter(arrest=="true",domestic=="false")
crime_2021 =
   read.csv("./data/Crimes_-_2021.csv") %>% 
   drop_na() %>% 
   janitor::clean_names() %>%
   filter(arrest=="true",domestic=="false")
```

```{r}
five_year_df=
   do.call("rbind",list(crime_2017, crime_2018, crime_2019,crime_2020, crime_2021)) %>% 
   mutate(
      date=strptime(date, "%m/%d/%Y %I:%M:%S %p"),
      date=as.Date(date,"%Y-%m-%d"),
      year = as.numeric(format(date, format = "%Y")),
      month = as.numeric(format(date, format = "%m")),
      day = as.numeric(format(date, format = "%d"))
      ) %>% 
   relocate(year,month,day,.before = date)
write.csv(five_year_df,file="./data/five_year_data.csv")
```