---
title: "Analyzing trends of Crime in Chicago"
output: 
  github_document:
    md_extensions: +tex_math_dollars
                   +raw_html
always_allow_html: yes
---

```{r setup and data import, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 300, out.width = "65%")
library(tidyverse)
library(leaflet)
library(lubridate)
library(ggExtra)
library(plotly)
library(maps)
library(mapdata)
library(ggthemes)
library(mapproj)
library(ggthemes)
library(gganimate)
library(viridis)
library(wordcloud)
library(RColorBrewer)
library(tm)
library(dplyr)
library(scales)
library(gganimate)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

|Name            | Uni       |
|----------------|-----------|
|Minxiu Shi      | ms6358    |
|Shengzhi Luo    | sl5009    |
|Yitian Zhang    | yz4185    |
|Yiwen Zhao      | yz4187    |


## **Introduction: **

This project is to research the ...
In this project, our team...

## **Data**

#### **Data Source**

6-year Chicago Crime data records are retrieved from Chicago’s official public data [Chicago Data Portal](https://data.cityofchicago.org). 

* 6-year Chicago crime data records (2016 - 2021):
  - [2016](https://data.cityofchicago.org/Public-Safety/Crimes-2016/kf95-mnd6/data)
  - [2017](https://data.cityofchicago.org/Public-Safety/Crimes-2017/d62x-nvdr/data)
  - [2018](https://data.cityofchicago.org/Public-Safety/Crimes-2018/3i3m-jwuy/data)
  - [2019](https://data.cityofchicago.org/Public-Safety/Crimes-2019/w98m-zvie/data)
  - [2020](https://data.cityofchicago.org/Public-Safety/Crimes-2020/qzdf-xmn8/data)
  - [2021](https://data.cityofchicago.org/Public-Safety/Crimes-2021/dwme-t96c/data)

This dataset reflects reported incidents of crime (with the exception of murders where data exists for each victim) that occurred in the City of Chicago from 2006 to present, minus the most recent seven days. Data is extracted from the Chicago Police Department's CLEAR (Citizen Law Enforcement Analysis and Reporting) system. In order to protect the privacy of crime victims, addresses are shown at the block level only and specific locations are not identified.  Each record represents one criminal case. This dataset contains approximately 2 million crime records and details 22 variables such as ID, number, data, neighborhood, IUCR, and primary type for each case.

## **Motivation: **

Due to the cases that happened in Chicago recently, the crime rates in different areas of Chicago caught our attention. Violent incidents in Chicago are of increasing concern over the last few years, and we are interested in looking at what might be associated with increased violence in Chicago. We are concerned about people’s living safety in the city and motivated to find safer neighborhoods for living in Chicago.


## **Study Questions: **

* q
* q
* q


## **Data Resource: **

6-year Chicago Crime data records are retrieved from Chicago’s official public data [Chicago Data Portal](https://data.cityofchicago.org). 

## **Exploratory Analysis: **

* **Figure1: **

* **Figure2: **

* **Figure3: **

* **Figure4: **

## **Results**


## **Discussion: **


## **Suggestion: **
