---
title: "P8105 Final Project Proposal"
date: "11/10/2021"
output: github_document
---

## The group members

  * Minxiu Shi (ms6358)
  * Shengzhi Luo (sl5009)
  * Yiwen Zhao (yz4187)
  * Yitian Zhang (yz4185)
  

## The tentative project title
Gotham City 


## Motivation

Due to the cases that happened in Chicago recently, the crime rates in different areas of Chicago caught our attention. Violent incidents in Chicago are of increasing concern over the last few years, and we are interested in looking at what might be associated with increased violence in Chicago. We are concerned about people’s living safety in the city and motivated to find safer neighborhoods for living in Chicago.


## The intended final products

* Website with static visualizations for statistical analyses, along with interactive map(s)

* Website will include links to data sources and interpretations of findings

* Screencast explaining website and analyses
 
 
## The anticipated data sources

* https://www.kaggle.com/chicago/chicago-crime

* https://data.cityofchicago.org/Public-Safety/Crimes-Map/dfnk-7re6

## The planned analyses / visualizations / coding challenges

  We hope to look at crime trends in Chicago over time, as well as crime trends geographically. Other factors may be taken into consideration for analysis, such as demographic characteristics, accessibility to police reporting, and time of incidents. A challenge that is not inherently a coding challenge but that is a data completeness challenge is the fact that excessive crimes pile up every year, resulting a huge dataset which requires us to do necessary selection and cleaning. Also, we have to figure out the variables we need including divison and filtering.


## Planned Timeline

| Due Dates        | Scheduled Tasks                                    |
| ---------------- | -------------------------------------------------- |
| 11/13            | Final project Proposal                             |
| 11/14-11/19      | Proposal Review & Get approved from instructor team|
| 11/20            | Make all data to be cleaned and ready for use      |
| 11/21-11/27      | Finish visualization and analysis                  |
| 11/28-12/4       | Working on webpages                                |
| 12/5-12/11       | Final editing and finish up deliverables           |